from pathlib import Path
import json
root=Path(__file__).parent/'dist'
icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" aria-hidden="true"><path d="M6 22V4l6-2 6 2v18M2 22V8h4m12 0h4v14M0 22h24M9 6v2m6-2v2M9 10v2m6-2v2M9 14v2m6-2v2M10 22v-4h4v4"/></svg>'
logo='<a class="logo" href="/" aria-label="INHELDER Startseite">INHELDER</a>'
links=[('projekt','Felsenstrasse 94/96'),('wohnungen','Wohnungen'),('unternehmen','Unternehmen'),('kontakt','Kontakt')]
def header(page):return f'<header>{logo}<button class="menu" aria-expanded="false" aria-controls="nav">Menü <span aria-hidden="true">☰</span></button><nav id="nav" aria-label="Hauptnavigation">'+''.join(f'<a {"aria-current=page" if page==p else ""} href="/{p}/">{t}</a>' for p,t in [('projekt','Projekt'),('unternehmen','Unternehmen'),('kontakt','Kontakt')])+f'<a class="button nav-cta" {"aria-current=page" if page=="wohnungen" else ""} href="/wohnungen/">Wohnungen entdecken <span aria-hidden="true">↗</span></a></nav></header>'
def footer():return f'<footer><div class="footer-main">{logo}<nav aria-label="Fussnavigation">'+''.join(f'<a href="/{p}/">{t}</a>' for p,t in links)+'</nav><a class="footer-email" href="mailto:dylan@inhelder.net" aria-label="E-Mail schreiben">↗</a></div><div class="footer-bottom"><span>© 2026 INHELDER</span><div><button data-legal="impressum">Impressum</button><button data-legal="datenschutz">Datenschutz</button></div></div></footer>'
def crumb(text):return f'<p class="crumb"><a href="/">Home</a> / {text}</p>'
def button(text,url,cls=''):return f'<a class="button {cls}" href="{url}">{text} <span aria-hidden="true">→</span></a>'
def model(cls=''):return f'<figure class="model {cls}"><img src="/assets/model.jpg" loading="lazy" alt="Platzhalter: Architekturmodell zweier historischer Wohnhäuser"><figcaption>Visualisierung · Platzhalter</figcaption></figure>'
def ph(text,sub='',cls=''):return f'<div class="placeholder {cls}"><span>＋</span><strong>{text}</strong><small>{sub or "Platzhalter · Inhalt folgt"}</small></div>'
def timeline():return '<div class="timeline">'+''.join(f'<div class="{"active" if i==1 else ""}"><span>{i+1}</span><small>{t}</small></div>' for i,t in enumerate(['Planung','Bewilligung','Ausführung','Innenausbau','Fertigstellung']))+'</div>'
legal='<dialog id="legal"><button class="close" aria-label="Schliessen">×</button><div id="legal-content"></div></dialog>'
home=f'''<section class="home-hero"><div class="hero-copy"><p class="eyebrow">INHELDER · ST. GALLEN</p><h1>Immobilien<br>mit Perspektive.</h1><p>Wir erhalten Charakter.<br>Und schaffen Raum für Neues.</p><div class="hero-actions">{button('Projekt entdecken','/projekt/')}<a class="text-link" href="/wohnungen/">Wohnungen ansehen <span aria-hidden="true">↗</span></a></div><span class="hero-signature">Architektur. Verantwortung. Bestand.</span></div><figure class="hero-photo"><img src="/assets/architecture.jpg" alt="Historische Wohnhäuser mit grünen Fensterläden – KI-generiertes Stimmungsbild" fetchpriority="high"><figcaption>Stimmungsbild · Platzhalter</figcaption></figure></section>
<section class="values" aria-label="Unsere Haltung"><article><span class="value-number">01</span><div><h3>Erhalten.</h3><p>Charakter bewahren.</p></div></article><article><span class="value-number">02</span><div><h3>Entwickeln.</h3><p>Wohnraum weiterdenken.</p></div></article><article><span class="value-number">03</span><div><h3>Verantworten.</h3><p>Langfristig handeln.</p></div></article></section>
<section class="home-grid"><article><p class="eyebrow">UNSER PROJEKT</p><h2>Felsenstrasse 94/96.<br>Ein neues Kapitel.</h2><p class="section-intro">Zwei historische Häuser. Zwölf geplante Wohnungen.<br>Mitten in St. Gallen.</p>{timeline()}<a class="text-link" href="/projekt/">Das Projekt kennenlernen <span aria-hidden="true">↗</span></a></article><article class="home-apartments"><div class="section-top"><p class="eyebrow">WOHNEN AN DER FELSENSTRASSE</p><span class="quiet-status">In Vorbereitung</span></div><h2>Ihr nächstes Zuhause.</h2>{model('mini')}{button('Wohnungen entdecken','/wohnungen/')}</article></section>
<section class="home-story"><div><p class="eyebrow">ÜBER INHELDER</p><h2>Persönlich engagiert.<br>Langfristig gedacht.</h2><p>Architektonisches Gespür.<br>Ein klarer Blick für bleibende Werte.</p><a class="text-link" href="/unternehmen/">Mehr über INHELDER <span aria-hidden="true">↗</span></a></div><figure><img src="/assets/entrance.jpg" alt="Historischer Hauseingang – Bildplatzhalter" loading="lazy"><figcaption>Stimmungsbild · Platzhalter</figcaption></figure></section>'''
project=f'''{crumb('Projekt / Felsenstrasse 94/96')}<section class="project-hero"><div><p class="eyebrow">BESTAND MIT ZUKUNFT</p><h1>Felsenstrasse<br>94/96.</h1><p>Zwei Häuser mit Geschichte.<br>Zeitgemässes Wohnen mit Charakter.</p><dl class="project-data"><div><dt>Standort</dt><dd>St. Gallen</dd></div><div><dt>Vorhaben</dt><dd>Sanierung & Weiterentwicklung</dd></div><div><dt>Planung</dt><dd>Forma Architekten</dd></div></dl>{button('Wohnungen entdecken','/wohnungen/')}</div>{model()}</section>
<div class="metrics"><div><strong>12</strong><span>Wohnungen geplant</span></div><div><strong>Um 1910</strong><span>Historischer Bestand</span></div><div><strong>Bezug</strong><span>Termin folgt</span></div></div>
<section class="project-progress"><div><p class="eyebrow">PROJEKTSTATUS</p>{timeline()}</div><div><h3>In der Bewilligungsphase.</h3><p>Der Entscheid steht noch aus.<br>Bestätigte Termine folgen hier.</p></div></section>
<section class="location"><div>{ph('Felsenstrasse 94/96','St. Gallen · Kartenplatzhalter','map-placeholder')}</div><div><p class="eyebrow">LAGE & UMGEBUNG</p><h2>In St. Gallen<br>zu Hause.</h2><p>Felsenstrasse 94/96<br>9000 St. Gallen</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Felsenstrasse+94+St.+Gallen" target="_blank" rel="noopener">Lage auf der Karte ansehen <span aria-hidden="true">↗</span></a></div></section><section class="milestones" id="termine"><p class="eyebrow">DIE NÄCHSTEN SCHRITTE</p><div><article><span>Bewilligung<small>Entscheid ausstehend</small></span></article><article><span>Baubeginn<small>Voraussichtlich November 2026</small></span></article><article><span>Vermietung<small>Informationen folgen</small></span></article><article><span>Bezug<small>Termin folgt</small></span></article></div></section>'''
apartments='''<section class="navigator-title"><div><h1>Wohnungen entdecken</h1><p>Geschoss wählen. Wohnung entdecken.</p></div><div class="view-tabs" role="tablist" aria-label="Wohnungsansicht"><button role="tab" aria-selected="true" data-view="model">Gebäude</button><button role="tab" aria-selected="false" data-view="plans">Grundrisse</button><button role="tab" aria-selected="false" data-view="list">Liste</button></div></section><p class="demo-note">Vorschau mit Beispieldaten · Noch kein verbindliches Mietangebot.</p><section class="navigator"><div class="floor-controls" aria-label="Geschoss wählen">'''+''.join(f'<button data-floor="{v}" aria-pressed="{str(v==2).lower()}">{label}</button>' for v,label in [(4,'Dachgeschoss'),(3,'3. Obergeschoss'),(2,'2. Obergeschoss'),(1,'1. Obergeschoss'),(0,'Erdgeschoss')])+f'''</div><div id="viewer">{model('navigator-model')}<a class="floating-card" id="selected-apartment" href="/wohnung/?id=2.3"><h3>Wohnung 2.3</h3><p>3.5 Zimmer <span>72 m²</span></p><p>CHF 1’980.– / Monat</p><small class="available">● Verfügbar</small><strong>Details ansehen →</strong></a><div class="plan-view" hidden>{ph('Geschossgrundriss','Geschossgrundriss folgt.')}</div></div><div class="legend"><span><i class="green"></i>Verfügbar</span><span><i class="gold"></i>Reserviert</span><span><i class="grey"></i>Vermietet</span><small>Beispielstatus</small></div></section><section class="apartment-results"><p id="floor-label">Aktuelles Geschoss: 2. Obergeschoss</p><div id="apartment-cards" class="apartment-cards"></div><div id="apartment-table" hidden></div><button class="text-link list-switch">Zur Listenansicht <span>→</span></button></section>'''
detail=f'''{crumb('<a href="/wohnungen/">Wohnungen</a> / <span id="detail-crumb">Wohnung 2.3</span>')}<p class="demo-note">Beispielwohnung · Angaben und Grundrisse sind Platzhalter.</p><section class="detail-main"><div><h1 id="detail-title">Wohnung 2.3</h1><p id="detail-summary">3.5 Zimmer · 72 m²</p><p id="detail-price">CHF 1’980.– / Monat</p><p class="detail-status available" id="detail-status">● Verfügbar</p>{button('Wohnung anfragen','/kontakt/?betreff=Wohnungsanfrage','inquiry')}<dl class="detail-data"><div><dt>◇ &nbsp; Wohnfläche</dt><dd id="detail-area">72 m²</dd></div><div><dt>⌂ &nbsp; Geschoss</dt><dd id="detail-floor">2. Obergeschoss</dd></div><div><dt>↕ &nbsp; Nassräume</dt><dd>Angaben folgen</dd></div><div><dt>▱ &nbsp; Balkon</dt><dd>Angaben folgen</dd></div><div><dt>◇ &nbsp; Parkplatz</dt><dd>Auf Anfrage</dd></div><div><dt>◷ &nbsp; Bezug</dt><dd>Termin folgt</dd></div></dl></div><div class="floorplan">{ph('Grundriss Wohnung 2.3','Grundriss folgt.','apartment-plan')}<span class="north">N ↑</span></div></section><section class="gallery">{ph('Wohnen / Essen')}{ph('Küche')}{ph('Schlafzimmer')}{ph('Bad')}</section>'''
company=f'''{crumb('Unternehmen')}<section class="company"><div><p class="eyebrow">ÜBER INHELDER</p><h1>Mit Haltung.<br>Mit Weitblick.</h1><p class="company-intro">Wir verbinden Architektur mit Verantwortung.<br>Für Immobilien, die langfristig überzeugen.</p><div class="company-values"><article><span class="value-number">01</span><div><h3>Persönlich.</h3><p>Direkte Wege. Klare Entscheidungen.</p></div></article><article><span class="value-number">02</span><div><h3>Sorgfältig.</h3><p>Respekt vor dem Bestand. Qualität im Detail.</p></div></article><article><span class="value-number">03</span><div><h3>Langfristig.</h3><p>Heute gestalten. Morgen weiterdenken.</p></div></article></div><div class="founder"><strong>Dylan Inhelder</strong><span>Architekt · INHELDER</span><a class="text-link" href="/kontakt/">Kontakt aufnehmen <span aria-hidden="true">↗</span></a></div></div><figure class="stair"><img src="/assets/stair.jpg" alt="Historisches Treppenhaus – Bildplatzhalter"><figcaption>Stimmungsbild · Platzhalter</figcaption></figure></section>'''
contact=f'''<section class="contact-page"><div><p class="eyebrow">KONTAKT</p><h1>Im Gespräch<br>beginnt Neues.</h1><p>Fragen zum Projekt oder einer Wohnung?<br>Wir freuen uns auf Ihre Nachricht.</p><article class="contact-card"><div><h3>Dylan Inhelder</h3><p>INHELDER · Projekt & Wohnungen</p><a href="tel:+41798890441">+41 79 889 04 41</a><a href="mailto:dylan@inhelder.net">dylan@inhelder.net</a></div><span>↗</span></article><article class="contact-card muted-card"><div><h3>Verwaltung</h3><p>Immobilienverwaltung</p><span class="placeholder-label">Kontakt wird ergänzt</span><p>Für Mieterschaft und Reparaturen.</p></div></article><address>INHELDER · Frongartenstrasse 4 · 9000 St. Gallen</address></div><div class="contact-form"><h3>Schreiben Sie uns.</h3><form id="contact-form"><div class="name-row"><label><span>Vorname</span><input name="firstName" placeholder="Vorname" autocomplete="given-name" required></label><label><span>Nachname</span><input name="lastName" placeholder="Nachname" autocomplete="family-name" required></label></div><label><span>E-Mail</span><input type="email" name="email" placeholder="E-Mail" autocomplete="email" required></label><label><span>Telefon (optional)</span><input type="tel" name="phone" placeholder="Telefon (optional)" autocomplete="tel"></label><label><span>Betreff</span><select name="subject" required><option value="">Betreff wählen</option><option>Wohnungsanfrage</option><option>Projekt Felsenstrasse</option><option>Zusammenarbeit</option><option>Allgemeine Anfrage</option></select></label><label><span>Nachricht</span><textarea name="message" placeholder="Nachricht" rows="7" required></textarea></label><label class="check"><input type="checkbox" required><span>Ich habe die <button type="button" data-legal="datenschutz">Datenschutzhinweise</button> gelesen.</span></label><button class="button submit" type="submit">Nachricht vorbereiten</button><p class="form-note">Öffnet einen Entwurf in Ihrem E-Mail-Programm.</p><p id="form-status" role="status"></p></form></div></section>'''
for page,title,body in [('', 'Immobilien mit Perspektive',home),('projekt','Felsenstrasse 94/96',project),('wohnungen','Wohnungen entdecken',apartments),('wohnung','Wohnungsdetails',detail),('unternehmen','Über INHELDER',company),('kontakt','Kontakt',contact)]:
 target=root/page;target.mkdir(exist_ok=True)
 html=f'''<!doctype html><html lang="de-CH"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} | INHELDER</title><meta name="description" content="INHELDER – Immobilien mit Perspektive. Entdecken Sie unser Projekt an der Felsenstrasse 94/96 in St. Gallen."><meta name="theme-color" content="#123d30"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%23123d30'/%3E%3Ctext x='16' y='25' text-anchor='middle' font-family='Georgia' font-size='27' fill='white'%3EI%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"></head><body data-page="{page or 'home'}"><a class="skip" href="#main">Zum Inhalt</a><div class="site-shell">{header(page)}<main id="main" class="page-{page or 'home'}">{body}</main>{footer()}</div>{legal}<script src="/script.js"></script></body></html>'''
 (target/'index.html').write_text(html)
print('Built six pages.')
